CREATE TABLE [dbo].[CalculationSettingItem]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,	
	[Name] NVARCHAR(32) NULL,	
	[Active] BIT NOT NULL DEFAULT 1, 
	[DateCreated] DATETIME NOT NULL DEFAULT GETDATE(),
	[DateUpdated] DATETIME NULL,
	[CreatedBy] INT NOT NULL,
	[UpdatedBy] INT NULL
)