CREATE TABLE [dbo].[CropProduction] /*Unidad Basica de cultivo dentro de production unit*/
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [CropId] INT NOT NULL, 
    [ProductionUnitId] INT NOT NULL, 
    [Name] NVARCHAR(128) NOT NULL,
	[ContainerId] INT NOT NULL,
    [GrowingMediumId] INT NOT NULL,
    [DropperId] INT NOT NULL,
    [Width] FLOAT NOT NULL,
	[Length] FLOAT NOT NULL, 
    [BetweenRowDistance] FLOAT NOT NULL,
    [BetweenContainerDistance] FLOAT NOT NULL,
	[BetweenPlantDistance] FLOAT NOT NULL,
	[PlantsPerContainer] INT NOT NULL, 
	[NumberOfDroppersPerContainer] INT NOT NULL, 
	[WindSpeedMeasurementHeight] FLOAT NOT NULL, 
    [StartDate] DATETIME NOT NULL, 
    [EndDate] DATETIME NOT NULL, 
	[Altitude] INT NOT NULL, 
	[Latitude] FLOAT NOT NULL,
	[Longitude] FLOAT NOT NULL,
	[DepletionPercentage] FLOAT NOT NULL,
	[DrainThreshold] FLOAT NOT NULL,
    [Active] BIT NOT NULL DEFAULT 1, 
	[DateCreated] DATETIME NOT NULL DEFAULT GETDATE(),
	[DateUpdated] DATETIME NULL,
	[CreatedBy] INT NOT NULL,
	[UpdatedBy] INT NULL,
    CONSTRAINT [FK_CropProduction_Crop] FOREIGN KEY ([CropId]) REFERENCES [Crop]([Id]),
    CONSTRAINT [FK_CropProduction_ToProductionUnit] FOREIGN KEY ([ProductionUnitId]) REFERENCES [ProductionUnit]([Id])
)
