//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriSmart.Tools.Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgriSmart.Tools.Desktop.Resources.FrmResources", typeof(FrmResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Companies.
        /// </summary>
        internal static string LoadingCompanies {
            get {
                return ResourceManager.GetString("LoadingCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Crop Phases.
        /// </summary>
        internal static string LoadingCropPhases {
            get {
                return ResourceManager.GetString("LoadingCropPhases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Crop Productions.
        /// </summary>
        internal static string LoadingCropProductions {
            get {
                return ResourceManager.GetString("LoadingCropProductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Crops.
        /// </summary>
        internal static string LoadingCrops {
            get {
                return ResourceManager.GetString("LoadingCrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Fertilizer Inputs &amp; Water.
        /// </summary>
        internal static string LoadingEntities {
            get {
                return ResourceManager.GetString("LoadingEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Farms.
        /// </summary>
        internal static string LoadingFarms {
            get {
                return ResourceManager.GetString("LoadingFarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Production Units.
        /// </summary>
        internal static string LoadingProductionUnits {
            get {
                return ResourceManager.GetString("LoadingProductionUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingSessionData.
        /// </summary>
        internal static string LoadingSessionData {
            get {
                return ResourceManager.GetString("LoadingSessionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loginFail.
        /// </summary>
        internal static string loginFail {
            get {
                return ResourceManager.GetString("loginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must create a session.
        /// </summary>
        internal static string NoSessionCreated {
            get {
                return ResourceManager.GetString("NoSessionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingData.
        /// </summary>
        internal static string WaitFormCaption {
            get {
                return ResourceManager.GetString("WaitFormCaption", resourceCulture);
            }
        }
    }
}
